name: Release new hpi

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
        
    - name: Step 3 - Build Maven Project
      run: mvn mvn install -DskipTests
    
    - name: Step 4 - List current directory
      run: ls -a 
    
    - name: Step 5 - What is in the target folder?
      run: |
        cd target
        ls -a 
        
        
        
        
    
#     - name: Create Release
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ github.ref }}
#         release_name: Release ${{ github.ref }}
#         draft: false
#         prerelease: false
#     - name: Upload hpi asset
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
#         asset_path: target/*.hpi
#         asset_name: xml-job-to-job-dsl.hpi
#         asset_content_type: application/java-archive
