name: Release Workflow
on:
  push:
    branches:
      - master 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses: actions/checkout@v2

    - name: Create release
      run: |
        version=$(date "+%Y.%m.%d")
        git tag v$version
        git push origin v$version
    - name: Create a release
      id: create_release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v$new_version
        release_name: Release v$new_version
        draft: false