name: Release Workflow
on:
  push:
    branches:
      - master 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses: actions/checkout@v2

    - name: Create release
      run: |
        version=$(date "+%Y.%m.%d")
        git tag v$version
        git push origin v$version