name: Release new hpi

# Run on every commit tag which begins with "v"
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest  
    steps: 
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
    
    - name: Upload hpi asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/*.hpi
        asset_name: xml-job-to-job-dsl.hpi
        asset_content_type: application/java-archive